import type { ActivityEvent, CodexCurrent, CodexProject, CodexSession, ContextPack, PageResponse } from "./codexWorkspaceTypes";
import type { CoreIntegrity, MemoryCandidate, ObsidianNote, ObsidianScan } from "./memoryReviewTypes";

export const mockCurrent: CodexCurrent = { project: { project_id: "project-demo", name: "LingJi", repository: "wangduoyu001/lingji", branch: "work/p2-07c-local-ui-loop", worktree_name: "p2-07c", path_display: "…/lingji", state: "active" }, session: { session_id: "session-demo", title: "P2-07C", project_id: "project-demo", status: "active", conversation_ids: ["conversation-demo"] }, mcp_state: "healthy", obsidian_state: "healthy", memory_index_state: "healthy", last_checkpoint_at: "2026-07-21T08:00:00Z", pending_review_count: 2 };
export const mockProjects: PageResponse<CodexProject> = { items: [mockCurrent.project!], pagination: { limit: 30, offset: 0, total: 1 } };
export const mockSessions: PageResponse<CodexSession> = { items: [{ ...mockCurrent.session!, goal: "完成本地 UI 记忆闭环", completed: ["DTO"], decisions: ["Mock first"], tests: ["Smoke"], blockers: [], next_steps: ["协调审查"], source_ids: ["source-demo"] }], pagination: { limit: 30, offset: 0, total: 1 } };
export const mockActivity: { items: ActivityEvent[] } = { items: [{ event_id: 1, occurred_at: "2026-07-21T08:01:00Z", project_id: "project-demo", session_id: "session-demo", stage: "CHECKPOINT_RECEIVED", summary: "收到检查点", status: "running" }] };
export const mockContext: ContextPack = { markdown: "# Project Context\n\n- Citation: source-demo", used_chars: 48, max_chars: 12000, sections: [{ type: "core_memory", title: "Core Memory", citations: ["source-demo"] }] };
export const mockCandidates: PageResponse<MemoryCandidate> = { items: [{ memory_id: "candidate-demo", title: "采用 Mock-first 并行开发", content_preview: "并行期间只依赖冻结合同", content: "并行期间只依赖冻结合同。", project_ids: ["project-demo"], proposed_by: "codex", importance: "high", confidence: 0.94, content_hash: "hash-demo", source_session_id: "session-demo", source_message_id: "message-demo", proposal_reason: "长期决策", affected_agents: ["codex"] }], pagination: { limit: 30, offset: 0, total: 1 } };
export const mockIntegrity: CoreIntegrity = { memory_id: "candidate-demo", state: "external_modified", relative_path: "02-Memory/Core/candidate-demo.md" };
export const mockNote: ObsidianNote = { title: "Demo", relative_path: "03-Knowledge/Notes/demo.md", content: "Demo", content_hash: "note-hash", metadata: { privacy: "private" } };
export const mockScan: ObsidianScan = { changed: 1, new: 1, missing: 0, external_modified_core: 1, indexed: 1, failed: 0, last_scan_at: "2026-07-21T08:02:00Z" };
