"""Persistent authorization and scan controls for automatic memory inputs."""

from .models import AuthorizationScope, DiscoveredSource, ScanRun, SourceRecord
from .source_registry import SourceRegistry
from .snapshot import ConsistentSnapshot, FileStat, SnapshotResult
from .checkpoint import CheckpointStore, ResumeToken, SnapshotJobRunner
from .watcher import AutomaticMemoryWatcher
from .scheduler import AutomaticMemoryScheduler, ReconciliationReport
from .runtime import AutomaticMemoryRuntime
from .discovery import discover_source_metadata
from .path_policy import enumerate_authorized_files
from .evaluation import (
    AcceptanceGate,
    AutomaticMemoryAcceptanceGate,
    CorpusRecord,
    EvaluationInputError,
    EvaluationQuestion,
    EvaluationReport,
    QuestionResult,
    evaluate_run,
    load_corpus,
    load_questions,
    score_question,
)
from .quality_gate import (
    AcceptanceCleanupError,
    AcceptanceRoots,
    build_expected_import_rows,
    EXPECTED_QUESTION_COUNT,
    generate_100k_history,
    run_100k_benchmark,
    run_quality_gate,
    temporary_acceptance_roots,
    publish_quality_envelope,
    runner_failure_envelope,
    cleanup_failure_envelope,
    ensure_4r2_ready_for_scale,
    QualityScaleBlockedError,
    validate_selected_evidence,
)
from .evidence_identity import (
    EvidenceIdentityError,
    EvaluationIdentityRegistry,
    MemorySectionIdentity,
    MessageIdentity,
    RawMessageSectionIdentity,
    SectionIdentity,
    SelectedEvidence,
    build_identity_registry,
    select_context_evidence,
)
from .quality_evidence import (
    CanonicalFunctionalEvidence,
    EvidenceState,
    ProtectedTreeInvalidError,
    ProtectedTreeSentinel,
    ProtectedTreeSentinelError,
    ProtectedTreeUnavailableError,
    QualityEvidenceReadiness,
    QualityPublicationError,
    QualityRunEnvelope,
    finalize_quality_envelope,
    write_quality_json_atomic,
    cleanup_inventory_before_delete,
    cleanup_inventory_after_delete,
    count_memory_projection_duplicates,
)
from .quality_degradation import (
    ContextBaselineMeasurement,
    CorruptionIsolationMeasurement,
    MCPParityMeasurement,
    measure_context_baseline,
    measure_corruption_isolation,
    measure_mcp_parity,
)

__all__ = [
    "AuthorizationScope",
    "ScanRun",
    "SourceRecord",
    "SourceRegistry",
    "ConsistentSnapshot",
    "FileStat",
    "SnapshotResult",
    "CheckpointStore",
    "ResumeToken",
    "SnapshotJobRunner",
    "AutomaticMemoryWatcher",
    "AutomaticMemoryScheduler",
    "ReconciliationReport",
    "AutomaticMemoryRuntime",
    "DiscoveredSource",
    "discover_source_metadata",
    "enumerate_authorized_files",
    "AcceptanceGate",
    "AutomaticMemoryAcceptanceGate",
    "CorpusRecord",
    "EvaluationInputError",
    "EvaluationQuestion",
    "EvaluationReport",
    "QuestionResult",
    "evaluate_run",
    "load_corpus",
    "load_questions",
    "score_question",
    "AcceptanceCleanupError",
    "AcceptanceRoots",
    "build_expected_import_rows",
    "EXPECTED_QUESTION_COUNT",
    "generate_100k_history",
    "run_100k_benchmark",
    "run_quality_gate",
    "temporary_acceptance_roots",
    "publish_quality_envelope",
    "runner_failure_envelope",
    "cleanup_failure_envelope",
    "ensure_4r2_ready_for_scale",
    "QualityScaleBlockedError",
    "validate_selected_evidence",
    "MessageIdentity",
    "EvaluationIdentityRegistry",
    "SelectedEvidence",
    "MemorySectionIdentity",
    "RawMessageSectionIdentity",
    "SectionIdentity",
    "EvidenceIdentityError",
    "build_identity_registry",
    "select_context_evidence",
    "EvidenceState",
    "CanonicalFunctionalEvidence",
    "QualityEvidenceReadiness",
    "QualityRunEnvelope",
    "ProtectedTreeSentinel",
    "ProtectedTreeSentinelError",
    "ProtectedTreeUnavailableError",
    "ProtectedTreeInvalidError",
    "QualityPublicationError",
    "finalize_quality_envelope",
    "write_quality_json_atomic",
    "cleanup_inventory_before_delete",
    "cleanup_inventory_after_delete",
    "count_memory_projection_duplicates",
    "ContextBaselineMeasurement",
    "CorruptionIsolationMeasurement",
    "MCPParityMeasurement",
    "measure_context_baseline",
    "measure_corruption_isolation",
    "measure_mcp_parity",
]
